name: webotp_autofill
description: "The WebOTP API provides a streamlined user experience for web apps to verify that a phone number belongs to a user when using it as a sign-in factor. WebOTP is an extension of the Credential Management API"
version: 0.0.5
homepage: https://github.com/gouthamsrikar/webotp_autofill
repository: https://github.com/gouthamsrikar/webotp_autofill

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      web:
